#include "check.hpp"

#include <cstring>
#include <fstream>

namespace testing {
std::vector<test_case>& registry() {
    static std::vector<test_case> r;
    return r;
}
}  // namespace testing

// --ctest-list <out.cmake> <exe> writes one add_test() per case, so the CTest
// entries are generated from the code rather than kept in step with it by hand.
static int write_ctest_list(const char* out, const char* exe) {
    std::ofstream f(out);
    if (!f) {
        std::fprintf(stderr, "cannot write %s\n", out);
        return 1;
    }
    f << "# generated by sentinel_tests --ctest-list, do not edit\n";
    for (const auto& t : testing::registry()) {
        f << "add_test(" << t.name << " \"" << exe << "\" " << t.name << ")\n";
    }
    return 0;
}

int main(int argc, char** argv) {
    if (argc == 4 && std::strcmp(argv[1], "--ctest-list") == 0) {
        return write_ctest_list(argv[2], argv[3]);
    }
    const char* filter = argc > 1 ? argv[1] : nullptr;

    int ran = 0, failed = 0;
    for (const auto& t : testing::registry()) {
        if (filter && t.name != filter) continue;
        std::vector<testing::failure> f;
        t.body(f);
        ++ran;
        if (f.empty()) {
            std::printf("[  ok  ] %s\n", t.name.c_str());
        } else {
            ++failed;
            std::printf("[ FAIL ] %s\n", t.name.c_str());
            for (const auto& x : f) {
                std::printf("         %s:%d  %s\n", x.file.c_str(), x.line, x.text.c_str());
            }
        }
    }
    if (filter && ran == 0) {
        std::printf("no test named %s\n", filter);
        return 2;
    }
    std::printf("\n%d case(s) run, %d failed\n", ran, failed);
    return failed == 0 ? 0 : 1;
}
