// Test material generated by the project itself.
//
// Nothing here is captured from a real connection and no real certificate is
// embedded anywhere in this repository. The TLS byte streams are assembled field
// by field against RFC 8446, the certificate hierarchy is encoded field by field
// against RFC 5280, and classic pcap files wrap those same bytes in Ethernet /
// IPv4 / TCP frames the project writes itself.
//
// When a system OpenSSL/libcrypto was linked at build time, the certificates are
// signed with keys generated for the fixture so signature verification can run.
// Without that backend the certificates carry a placeholder signature value and
// the validator reports the check as skipped. Both behaviours are deliberate.
#pragma once

#include <cstdint>
#include <set>
#include <string>
#include <vector>

namespace sentinel::fixtures {

// A complete TLS 1.3 exchange as a passive reader would see it: ClientHello,
// ServerHello, the compatibility ChangeCipherSpec, then protected records.
// The ServerHello is deliberately split across two records so that the
// reassembly path is exercised rather than assumed.
std::vector<std::uint8_t> tls13_stream(const std::string& server_name = "sentinel.example.test",
                                       bool split_server_hello = true);

// A server that answered with TLS 1.2 and set the RFC 8446 downgrade sentinel,
// while the client had offered TLS 1.3.
std::vector<std::uint8_t> tls12_downgrade_stream();

// A ClientHello whose extension block claims more bytes than the record holds.
std::vector<std::uint8_t> truncated_stream();

// Classic pcap (LINKTYPE_ETHERNET) wrapping a TLS byte stream as IPv4/TCP
// payloads split across one or more frames. Built from the project's own bytes.
std::vector<std::uint8_t> tls_stream_as_pcap(const std::vector<std::uint8_t>& tls_bytes,
                                            std::size_t payload_per_frame = 512);

struct chain_case {
    std::string name;
    std::string server_name;
    std::vector<std::vector<std::uint8_t>> der;  // end entity first
    bool expect_accepted = false;
    std::string expectation;  // what should happen, and why
};

struct pki {
    std::vector<std::uint8_t> root_der;
    std::vector<std::uint8_t> intermediate_der;
    std::set<std::string> revoked_serials;
    std::vector<chain_case> cases;
};

// Builds the whole hierarchy relative to a reference time, so that the expired
// and not-yet-valid cases stay expired and not yet valid whenever it is run.
pki build_pki(std::int64_t now);

}  // namespace sentinel::fixtures
