// The full measurement run.
//
// Longer budgets and more repetitions than the demonstration, and it prints the
// individual repetitions as well as the median, so that every summarised number
// in the report can be traced back to the values it came from.
//
//   ./build/sentinel_bench [--duration-ms N] [--repeat N] [--honest N] [--flood N]
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "sentinel/experiment.hpp"

namespace {

void heading(const char* title) {
    std::printf("\n==============================================================================\n");
    std::printf("  %s\n", title);
    std::printf("==============================================================================\n\n");
}

void print_samples(const char* label, const sentinel::experiment::sample_set& s, int decimals) {
    std::printf("      %-22s", label);
    for (double v : s.values) std::printf(" %.*f", decimals, v);
    std::printf("   | median %.*f, iqr %.1f%%, range %.1f%%\n", decimals, s.median(),
                s.relative_iqr() * 100.0, s.relative_range() * 100.0);
}

int int_arg(int argc, char** argv, const char* name, int fallback) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (std::strcmp(argv[i], name) == 0) return std::atoi(argv[i + 1]);
    }
    return fallback;
}

}  // namespace

int main(int argc, char** argv) {
    const int duration_ms = int_arg(argc, argv, "--duration-ms", 700);
    const int repeat = int_arg(argc, argv, "--repeat", 9);
    const int honest = int_arg(argc, argv, "--honest", 2);
    const int flood = int_arg(argc, argv, "--flood", 4);

    std::printf("Sentinel measurement run. Defensive only: the load is generated by this\n");
    std::printf("process against its own listener on the loopback interface.\n\n");
    std::printf("machine:\n  %s\n", sentinel::experiment::machine_description().c_str());
    std::printf("\nparameters:\n");
    std::printf("  load duration per repetition : %d ms\n", duration_ms);
    std::printf("  repetitions per configuration: %d\n", repeat);
    std::printf("  honest client threads        : %d\n", honest);
    std::printf("  flood client threads         : %d\n", flood);

    heading("Parsing and validation");
    std::vector<sentinel::experiment::throughput_row> rows;
    rows.push_back(sentinel::experiment::measure_tls_parse(250'000'000, repeat));
    rows.push_back(sentinel::experiment::measure_certificate_parse(250'000'000, repeat));
    rows.push_back(sentinel::experiment::measure_chain_validation(250'000'000, repeat));
    std::printf("%s\n", sentinel::experiment::render_throughput(rows).c_str());
    std::printf("  individual repetitions, nanoseconds per operation:\n");
    for (const auto& r : rows) print_samples(r.name.substr(0, 20).c_str(), r.ns_per_operation, 1);

    heading("Admission decision cost inside the process");
    std::vector<sentinel::experiment::decision_cost> costs;
    for (const auto& cfg : sentinel::experiment::standard_configurations()) {
        costs.push_back(sentinel::experiment::measure_decision_cost(cfg, 150'000'000, repeat));
    }
    std::printf("%s\n", sentinel::experiment::render_decision_costs(costs).c_str());
    std::printf("  individual repetitions, nanoseconds per decision:\n");
    for (const auto& c : costs) print_samples(c.configuration.substr(0, 20).c_str(), c.ns_per_decision, 1);

    heading("Under flood, over loopback TCP");
    sentinel::experiment::load_params p;
    p.duration_ns = static_cast<std::int64_t>(duration_ms) * 1'000'000;
    p.repetitions = repeat;
    p.honest_threads = honest;
    p.flood_threads = flood;
    const auto load = sentinel::experiment::run_load_sweep(p);
    std::printf("%s\n", sentinel::experiment::render_load(load).c_str());

    std::printf("  individual repetitions:\n");
    for (const auto& r : load) {
        std::printf("    %s\n", r.configuration.c_str());
        print_samples("admitted per second", r.admitted_per_second, 0);
        print_samples("p50 latency us", r.p50_us, 1);
        print_samples("p95 latency us", r.p95_us, 1);
        print_samples("decisions per second", r.decisions_per_second, 0);
        std::printf("      %-22s offered %llu, admitted %llu, refused %llu, peak table %zu\n",
                    "totals of last run", static_cast<unsigned long long>(r.offered),
                    static_cast<unsigned long long>(r.admitted),
                    static_cast<unsigned long long>(r.refused), r.peak_table);
    }

    // The validity rule from the method: a set of repetitions whose spread is
    // too wide is reported as unusable rather than averaged into a number that
    // looks calm.
    heading("Validity of this run");
    bool all_tight = true;
    auto judge = [&all_tight](const char* what, const sentinel::experiment::sample_set& s,
                              double limit) {
        const double spread = s.relative_iqr();
        const bool ok = spread <= limit;
        all_tight = all_tight && ok;
        std::printf("  %-64s iqr %5.1f%%  range %6.1f%%  %s\n", what, spread * 100.0,
                    s.relative_range() * 100.0,
                    ok ? "within the limit" : "TOO WIDE, do not report this row");
    };
    for (const auto& r : rows) judge(r.name.c_str(), r.ns_per_operation, 0.25);
    for (const auto& c : costs) judge(c.configuration.c_str(), c.ns_per_decision, 0.35);
    for (const auto& r : load) judge(r.configuration.c_str(), r.admitted_per_second, 0.40);
    std::printf("\n  %s\n", all_tight ? "every row is inside its spread limit."
                                      : "at least one row exceeded its spread limit.");
    return 0;
}
