// One command that shows the whole system working.
//
//   cmake --build build --target demo
//   or: ./build/sentinel_demo
//
// Three parts, in the order the report describes them: read a TLS 1.3 handshake
// out of raw bytes, validate a certificate chain and say which checks ran, then
// measure what each admission control costs against the project's own loopback
// listener.
#include <chrono>
#include <cstdio>
#include <string>
#include <vector>

#include "sentinel/chain.hpp"
#include "sentinel/crypto.hpp"
#include "sentinel/experiment.hpp"
#include "sentinel/fixtures.hpp"
#include "sentinel/pcap.hpp"
#include "sentinel/tls.hpp"
#include "sentinel/x509.hpp"

namespace {

using sentinel::bytes_view;

bytes_view view(const std::vector<std::uint8_t>& v) { return bytes_view(v.data(), v.size()); }

void heading(const char* title) {
    std::printf("\n==============================================================================\n");
    std::printf("  %s\n", title);
    std::printf("==============================================================================\n\n");
}

void show_stream(const char* label, const std::vector<std::uint8_t>& stream) {
    std::printf("--- %s (%zu bytes on the wire) ---\n", label, stream.size());
    auto scan = sentinel::tls::scan_stream(view(stream));
    if (!scan) {
        std::printf("  refused: %s\n\n", scan.error().c_str());
        return;
    }
    auto report = sentinel::tls::summarise(*scan);
    if (!report) {
        std::printf("  refused: %s\n\n", report.error().c_str());
        return;
    }
    std::printf("%s\n", sentinel::tls::render(*report).c_str());
}

std::int64_t wall_clock_seconds() {
    return std::chrono::duration_cast<std::chrono::seconds>(
               std::chrono::system_clock::now().time_since_epoch())
        .count();
}

}  // namespace

int main() {
    std::printf(
        "Sentinel: transport security analysis and connection admission control.\n"
        "Defensive only. Every byte read below was generated by this repository, and the\n"
        "load in the last section is generated by this process against its own listener on\n"
        "the loopback interface.\n");

    // -----------------------------------------------------------------------
    heading("1. TLS 1.3 handshake, read from raw bytes and from a classic pcap");
    show_stream("complete TLS 1.3 exchange", sentinel::fixtures::tls13_stream());
    {
        const auto tls = sentinel::fixtures::tls13_stream("sentinel.example.test", true);
        const auto cap = sentinel::fixtures::tls_stream_as_pcap(tls, 300);
        auto extracted =
            sentinel::pcap::tls_stream_from_pcap(view(cap));
        std::printf("--- same exchange, recovered from a generated classic pcap (%zu file bytes) ---\n",
                    cap.size());
        if (!extracted) {
            std::printf("  refused: %s\n\n", extracted.error().c_str());
        } else {
            show_stream("pcap-extracted TLS stream", *extracted);
        }
    }
    show_stream("server answered TLS 1.2 while the client offered TLS 1.3",
                sentinel::fixtures::tls12_downgrade_stream());
    std::printf("--- a handshake message cut short inside its record ---\n");
    {
        const auto broken = sentinel::fixtures::truncated_stream();
        auto scan = sentinel::tls::scan_stream(view(broken));
        std::printf("  refused: %s\n", scan.ok() ? "accepted, which is wrong" : scan.error().c_str());
    }

    // -----------------------------------------------------------------------
    heading("2. X.509 chain validation, with signature status named honestly");

    const std::int64_t now = wall_clock_seconds();
    const auto pki = sentinel::fixtures::build_pki(now);

    sentinel::chain::trust_store store;
    if (auto root = sentinel::x509::parse_certificate(view(pki.root_der))) {
        store.anchors.push_back(*root);
        std::printf("trust anchor: %s\n", root->summary().c_str());
    }
    store.revoked_serials = pki.revoked_serials;
    store.revocation_data_current = true;
    std::printf("local revocation list: %zu serial number(s)\n", store.revoked_serials.size());
    std::printf("cryptographic backend: %s\n", sentinel::crypto::backend_name().c_str());
    if (sentinel::crypto::available()) {
        std::printf(
            "\nThe hierarchy is generated and signed by this program using the system\n"
            "OpenSSL/libcrypto. Signature verification runs and is reported as PASS or FAIL.\n\n");
    } else {
        std::printf(
            "\nThe hierarchy is generated by this program. No real third-party certificate is\n"
            "embedded, and without a cryptographic backend the certificates carry a placeholder\n"
            "signature; the signature check is reported as SKIP.\n\n");
    }

    int agreed = 0;
    for (const auto& c : pki.cases) {
        std::vector<sentinel::x509::certificate> presented;
        for (const auto& der : c.der) {
            if (auto p = sentinel::x509::parse_certificate(view(der))) presented.push_back(*p);
        }
        sentinel::chain::options opt;
        opt.at_time = now;
        opt.server_name = c.server_name;
        const auto report = sentinel::chain::validate(presented, store, opt);
        const bool as_expected = report.accepted == c.expect_accepted;
        agreed += as_expected ? 1 : 0;
        std::printf("--- case: %s ---\n", c.name.c_str());
        std::printf("  requested host              : %s\n", c.server_name.c_str());
        std::printf("  expected                    : %s\n", c.expectation.c_str());
        std::printf("%s", sentinel::chain::render(report).c_str());
        std::printf("  matches the expectation     : %s\n\n", as_expected ? "yes" : "NO");
    }
    std::printf("%d of %zu cases produced the verdict they were built for.\n", agreed,
                pki.cases.size());

    // -----------------------------------------------------------------------
    heading("3. What each admission control costs");
    std::printf("machine:\n  %s\n\n", sentinel::experiment::machine_description().c_str());

    std::printf("Parsing and validation throughput:\n\n");
    std::vector<sentinel::experiment::throughput_row> rows;
    rows.push_back(sentinel::experiment::measure_tls_parse(120'000'000, 3));
    rows.push_back(sentinel::experiment::measure_certificate_parse(120'000'000, 3));
    rows.push_back(sentinel::experiment::measure_chain_validation(120'000'000, 3));
    std::printf("%s\n", sentinel::experiment::render_throughput(rows).c_str());

    std::printf("Cost of one admission decision, measured inside the process:\n\n");
    std::vector<sentinel::experiment::decision_cost> costs;
    for (const auto& cfg : sentinel::experiment::standard_configurations()) {
        costs.push_back(sentinel::experiment::measure_decision_cost(cfg, 60'000'000, 3));
    }
    std::printf("%s\n", sentinel::experiment::render_decision_costs(costs).c_str());

    std::printf(
        "Under flood, over real TCP connections on loopback. Two honest clients complete\n"
        "the exchange, four flood clients open connections and never answer.\n\n");
    sentinel::experiment::load_params p;
    p.duration_ns = 300'000'000;
    p.repetitions = 2;
    const auto load = sentinel::experiment::run_load_sweep(p);
    std::printf("%s\n", sentinel::experiment::render_load(load).c_str());

    std::printf(
        "Run sentinel_bench for the full measurement with more repetitions, which is what\n"
        "the numbers in the report are taken from.\n");
    return agreed == static_cast<int>(pki.cases.size()) ? 0 : 1;
}
